version: '3'
services:
  ebiznes:
    build: .
    ports:
      - 12345: 9000
      - 12346: 3000
    volumes:
      - ./:/home/amichno/projekt/shop
    working_dir: /home/amichno/projekt/shop
    command: sbt run