# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shop-scala

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_924291c1d9e44462a77f09ccd59b438d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_62a4043067284dccabda032db0d3fdd8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_924291c1d9e44462a77f09ccd59b438d }}/amichno/ebiznes:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shop-scala'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e9189883c004449ea995391f4866d3db }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_924291c1d9e44462a77f09ccd59b438d }}/amichno/ebiznes:${{ github.sha }}'